import Vue from "vue";
import {
    Col,
    Row,
    Button,
    Layout,
    // Color,
    // Font,
    Icon,
    List,
    // ListItem,
    Card,
    Collapse,
    Panel,
    Divider,
    CellGroup,
    Cell,
    Switch,
    Menu,
    MenuItem,
    Submenu,
    MenuGroup,
    Tabs,
    TabPane,
    Dropdown,
    DropdownMenu,
    DropdownItem,
    Page,
    Breadcrumb,
    BreadcrumbItem,
    Badge,
    Anchor,
    AnchorLink,
    Steps,
    Step,
    Input,
    Radio,
    RadioGroup,
    Checkbox,
    CheckboxGroup,
    Split,
    Table,
    Select,
    Option,
    AutoComplete,
    Slider,
    DatePicker,
    TimePicker,
    Cascader,
    Transfer,
    InputNumber,
    Rate,
    Upload,
    ColorPicker,
    Form,
    FormItem,
    Alert,
    Modal,
    Drawer,
    Tree,
    Tooltip,
    Poptip,
    Progress,
    Avatar,
    Tag,
    Carousel,
    CarouselItem,
    Timeline,
    TimelineItem,
    Time,
    Circle,
    Affix,
    BackTop,
    Spin,
    Scroll
} from "view-design" ;
Vue.component("Button",Button);
Vue.component("Col",Col);
Vue.component("Row",Row);
Vue.component("Layout",Layout);
// Vue.component("Color",Color);
// Vue.component("Font",Font);
Vue.component("Icon",Icon);
Vue.component("List",List);
// Vue.component("ListItem",ListItem);
Vue.component("Card",Card);
Vue.component("Collapse",Collapse);
Vue.component("Panel",Panel);
Vue.component("Divider",Divider);
Vue.component("CellGroup",CellGroup);
Vue.component("Cell",Cell);
Vue.component("Switch",Switch);
Vue.component("Menu",Menu);
Vue.component("MenuItem",MenuItem);
Vue.component("Submenu",Submenu);
Vue.component("MenuGroup",MenuGroup);
Vue.component("Tabs",Tabs);
Vue.component("TabPane",TabPane);
Vue.component("Dropdown",Dropdown);
Vue.component("DropdownMenu",DropdownMenu);
Vue.component("DropdownItem",DropdownItem);
Vue.component("Page",Page);
Vue.component("Breadcrumb",Breadcrumb);
Vue.component("BreadcrumbItem",BreadcrumbItem);
Vue.component("Badge",Badge);
Vue.component("Anchor",Anchor);
Vue.component("AnchorLink",AnchorLink);
Vue.component("Steps",Steps);
Vue.component("Step",Step);
Vue.component("Input",Input);
Vue.component("Radio",Radio);
Vue.component("RadioGroup",RadioGroup);
Vue.component("Checkbox",Checkbox);
Vue.component("CheckboxGroup",CheckboxGroup);
Vue.component("Split",Split);
Vue.component("Table",Table);
Vue.component("Select",Select);
Vue.component("Option",Option);
Vue.component("AutoComplete",AutoComplete);
Vue.component("Slider",Slider);
Vue.component("DatePicker",DatePicker);
Vue.component("TimePicker",TimePicker);
Vue.component("Cascader",Cascader);
Vue.component("Transfer",Transfer);
Vue.component("InputNumber",InputNumber);
Vue.component("Rate",Rate);
Vue.component("Upload",Upload);
Vue.component("ColorPicker",ColorPicker);
Vue.component("Form",Form);
Vue.component("FormItem",FormItem);
Vue.component("Alert",Alert);
Vue.component("Modal",Modal);
Vue.component("Drawer",Drawer);
Vue.component("Tree",Tree);
Vue.component("Tooltip",Tooltip);
Vue.component("Poptip",Poptip);
Vue.component("Progress",Progress);
Vue.component("Avatar",Avatar);
Vue.component("Tag",Tag);
Vue.component("Carousel",Carousel);
Vue.component("CarouselItem",CarouselItem);
Vue.component("Timeline",Timeline);
Vue.component("TimelineItem",TimelineItem);
Vue.component("Time",Time);
Vue.component("Circle",Circle);
Vue.component("Affix",Affix);
Vue.component("BackTop",BackTop);
Vue.component("Spin",Spin);
Vue.component("Scroll",Scroll);